name: iga_attachment
channels:
  - conda-forge
  - defaults

dependencies:
  # Core scientific stack
  - python=3.10
  - numpy>=1.25
  - pandas>=2.2
  - scipy>=1.11
  - matplotlib>=3.8
  - seaborn>=0.13

  # Bayesian inference and probabilistic modeling
  - pymc>=5.10
  - arviz>=0.16

  # Machine learning and evaluation
  - scikit-learn>=1.5
  - xgboost>=2.0
  - lightgbm>=4.2
  - shap>=0.45

  # Statistical tests and effect sizes
  - pingouin>=0.5
  - statsmodels>=0.14

  # Dimensionality reduction and embeddings
  - umap-learn>=0.5
  - scikit-learn-extra>=0.3

  # Visualization and interpretability
  - plotly>=5.24
  - graphviz>=0.20
  - pydot>=1.4
  - pillow>=10.0

  # Data handling and utilities
  - openpyxl>=3.1
  - joblib>=1.3
  - tqdm>=4.66

  # Notebook environment
  - jupyterlab>=4.1
  - notebook>=7.0
  - ipywidgets>=8.1
  - matplotlib-inline>=0.1

  # Code formatting and reproducibility (optional)
  - black>=24.3
  - flake8>=7.0
  - isort>=5.13

  # Export and documentation (optional)
  - pdfkit>=1.0

  # Ensure C/C++ compilers for PyMC / Numba backend
  - gcc
  - libgcc
  - libstdcxx-ng

  # Optional pip-installed packages
  - pip
  - pip:
      - multicoretsne>=0.1
      - plotnine>=0.12
      - kaleido>=0.2
